print("test1")
print("O-CODE1")
print("O-CODE1")
print("O-CODE1")
print("O-COD1")
print("O-CODE1")
print("C-CODE1")
print("C-CODE1")
print("O-CODE1")
print("O-CODE1")

print("O-CODE1")
print("O-ODE1")
print("O-CODE1")
